apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            namespace: sample-app-staging
          - env: production
            namespace: sample-app-prod
  template:
    metadata:
      name: 'sample-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hkotaga-source/argocd-gitops-demo.git
        targetRevision: HEAD
        path: apps/sample-app
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
